/*
Author      : Naveen Varshney
Description : This Class is Test class for UnarchivedSelectedReports.apxc
*/
@isTest
public with sharing class UnarchivedSelectedReportTest{
    /*@isTest(SeeAllData='true')
    static void testMethodForApexClass(){
        Test.startTest();
        UnarchivedSelectedReports classObj = new UnarchivedSelectedReports();
        System.assertNotEquals(null, classObj.reportsList);
        Test.stopTest();
    }*/
}